# Generated by Django 4.2.14 on 2025-01-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('Data Analysis', 'Data Analysis'), ('Marketing', 'Marketing'), ('Digital Marketing', 'Digital Marketing'), ('Others', 'Others')], default='Others', max_length=50)),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('budget', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Testing', 'Testing'), ('UI design', 'UI design'), ('Bug', 'Bug'), ('Support', 'Support'), ('Front end', 'Front end'), ('Database', 'Database'), ('Others', 'Others')], default='Others', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(help_text='Estimated hours to complete the task.')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taskprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='admin_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks_assigned', to='admin_app.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.sprint'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.ManyToManyField(related_name='assigned_projects', to='admin_app.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
