# Generated by Django 4.2.14 on 2025-01-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_sprint_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
    ]
