# Generated by Django 4.2.14 on 2025-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_sprints', to='admin_app.task'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='in_progress_tasks',
            field=models.ManyToManyField(blank=True, related_name='in_progress_sprints', to='admin_app.task'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='pending_tasks',
            field=models.ManyToManyField(blank=True, related_name='pending_sprints', to='admin_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Backlog', 'Backlog')], default='Backlog', max_length=50),
        ),
    ]
