# Generated by Django 4.2.14 on 2025-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_sprint_completed_tasks_sprint_in_progress_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=6, max_length=255),
            preserve_default=False,
        ),
    ]
