# Generated by Django 4.2.14 on 2025-02-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_user_role_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
