# Generated by Django 4.2.14 on 2025-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('New Development', 'New Development'), ('Enhancements', 'Enhancements'), ('Maintenance', 'Maintenance'), ('Web Development', 'Web Development')], max_length=50)),
            ],
        ),
    ]
