# Generated by Django 4.2.14 on 2025-02-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_projectfunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='function',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.projectfunctions'),
            preserve_default=False,
        ),
    ]
