# Generated by Django 4.2.14 on 2025-02-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfunctions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.project'),
        ),
    ]
