# Generated by Django 4.2.14 on 2025-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_projectfunctions_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.project'),
        ),
        migrations.DeleteModel(
            name='Project_details',
        ),
    ]
