# Generated by Django 4.2.14 on 2025-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_timelineevent_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date',
            field=models.DateField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date',
            field=models.DateField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
