# Generated by Django 4.2.14 on 2025-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_remove_timelineevent_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
