# Generated by Django 4.2.14 on 2025-01-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktime',
            options={'ordering': ['-start_time']},
        ),
    ]
