# Generated by Django 4.2.14 on 2025-01-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_tasktime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktime',
            options={},
        ),
    ]
