# Generated by Django 4.2.14 on 2025-01-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_sprint_completed_tasks_sprint_in_progress_tasks_and_more'),
        ('employee_app', '0003_alter_tasktime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktime',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_times', to='admin_app.task'),
        ),
    ]
