# Generated by Django 4.2.14 on 2025-01-30 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_tasktime_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
