# Generated by Django 4.2.14 on 2025-01-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_tasktime_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktime',
            name='total_time',
        ),
    ]
