# Generated by Django 4.2.14 on 2025-02-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_delete_comment'),
        ('employee_app', '0006_remove_tasktime_total_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user')),
            ],
        ),
    ]
