# Generated by Django 4.2.14 on 2025-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
