# Generated by Django 4.2.14 on 2025-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_tasktime_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='total_duration',
            field=models.FloatField(default=0),
        ),
    ]
