# Generated by Django 4.2.14 on 2025-02-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_tasktime_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktime',
            name='total_duration',
        ),
    ]
