# Generated by Django 4.2.14 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_remove_tasktime_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
